export default {
	"Atlanta": "ATL",
	"Anaheim": "SNA",
	"Saint Petersburg": "TPA",
	"Oakland": "OAK",
	"Denver": "DEN",
	"Bronx": "JFK",
	"Toronto": "YBZ",
	"Arlington": "DFW",
	"Phoenix": "PHX",
	"Baltimore": "BWI",
	"Seattle": "SEA",
	"Cleveland": "CLE",
	"Los Angeles": "LAX", 
	"St. Louis": "STL",
	"Philadelphia": "PHL",
	"Milwaukee": "MKE",
	"San Diego": "SAN",
	"Cincinnati": "CVG",
	"Washington": "DCA",
	"New York": "LGA",
	"San Francisco": "SFO",
	"Chicago": "ORD",
	"Detroit": "DTW",
	"Houston": "HOU",
	"Kansas City": "MCI",
	"Minneapolis": "MSP",
	"Boston": "BOS",
	"Pittsburgh": "PIT",
	"Miami": "MIA"
}